licenses(["notice"])

package(default_visibility = ["//visibility:public"])

java_library(
    name = "xml",
    srcs = glob(["**/*.java"]),
    deps = [
        "//java/com/khulnasoft/bitclone/config:base",
        "//java/com/khulnasoft/bitclone/doc:annotations",
        "//java/com/khulnasoft/bitclone/exception",
        "//third_party:starlark",
    ],
)
