package(default_visibility = ["//visibility:public"])

licenses(["notice"])

java_library(
    name = "credentials",
    srcs = glob(["*.java"]),
    deps = [
        "//java/com/khulnasoft/bitclone:options",
        "//java/com/khulnasoft/bitclone/exception",
        "//java/com/khulnasoft/bitclone/util/console",
        "//third_party:autovalue",
        "//third_party:guava",
        "//third_party:jsr305",
        "//third_party:starlark",
        "//third_party:tomlj",
    ],
)
